### ISSUE TITLE
Tag repository to make it discoverable

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/html2doc#1]

**Comment by ronaldtse** [comment]
Done!

**Comment by opoudjis** [comment]
Sorry, misused term. I meant "topics": https://help.github.com/articles/classifying-your-repository-with-topics/

https://github.com/MuhammetDilmac/Html2Docx has used: ruby, docx, html, docx-generator. https://github.com/jetruby/puredocx has used gem, docx, docx-generator, ruby, microsoft-word

We should put in: docx, docx-generator, microsoft-word, html, doc

You'll need to do it, I'm not admin on repo. Consider putting topics elsewhere in ribose github.

**Comment by ronaldtse** [comment]
Oooh I didn't even notice this feature before. Done.

**Comment by opoudjis** [comment]
Me neither, just found it at Html2Docx, but it is useful.
