### ISSUE TITLE
Use mathml2omml.xsl from TEI-C

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/html2doc#13]
https://github.com/TEIC/Stylesheets/blob/dev/docx/to/mml2omml.xsl

Prerelease version, so can be redistributed. At least, TEI have been redistributing it for the past 5 years.

Need to reference TEI in credits.

**Comment by opoudjis** [comment]
https://github.com/TEIC/Stylesheets/blob/dev/LICENCE

**Comment by ronaldtse** [comment]
Excellent -- we should actually change our license to BSD to be compatible.
