### ISSUE TITLE
Ruby version

### ISSUE THREAD

**Issue by edsontrick** [riboseinc/html2doc#14]
Can you downgrade the ruby version requirement to 2.3.1 ? Any special reason for version 2.4.0?

**Comment by ronaldtse** [comment]
@edsontrick indeed we could downgrade, but since we don't develop against it, it is hard for us to guarantee things work.

Let's first see the results here: https://github.com/riboseinc/html2doc/pull/15

**Comment by edsontrick** [comment]
There are problems on travis checks =/

**Comment by opoudjis** [comment]
Removed `match?`.

**Comment by opoudjis** [comment]
Works with 2.3 now. Ruby 2.2 does not understand the description field in gemspec; we're treating 2.2 as a wontfix.

**Comment by ronaldtse** [comment]
Thanks @opoudjis ! @edsontrick it works for 2.3 now -- is it good enough for you?

**Comment by edsontrick** [comment]
Nice nice nice !!!
