### ISSUE TITLE
Opinion

### ISSUE THREAD

**Issue by edsontrick** [riboseinc/html2doc#16]
How about pass the full path to the img src instead of only the complementary path to a fixed place like "file://C//Doc" ?

**Comment by ronaldtse** [comment]
I'm in favor of more fine grained control, and sounds like @opoudjis is too 😉

**Comment by opoudjis** [comment]
there are constraints in terms of what Word can actually understand, and Word does expect to find all its images in the one place. The source document may have images scattered all over the place, and this gem gathers them in the same place for inclusion as MIME attachments to Word. I will confirm that the source document is not expected to have its images all in the one place, but so long as it does not, nothing else needs to be done: Word will find the images where it expects to see them.

**Comment by ronaldtse** [comment]
As long as `html2doc` can consolidate all the images into the same place for Word (Word has to package them inside a `doc` file anyway), where the original image sources are should be fine.

**Comment by edsontrick** [comment]
But, today, it doesn't works with external url for images. Like S3, for example.

**Comment by ronaldtse** [comment]
That's an interesting case. Are you thinking of a Word document that directly uses an image from S3 (dynamic), or are you looking at a Word document that "embeds" an image originally from S3 (static)?

**Comment by edsontrick** [comment]
Yes, I think that it can be the two cases. The easiest one.

**Comment by opoudjis** [comment]
https://superuser.com/questions/38870/in-microsoft-word-how-can-i-link-to-an-image-from-the-web-which-updates

Huh. Well, let's see what this looks like in Word HTML...

**Comment by opoudjis** [comment]
It'll work: I just need to ignore Image sources during document generation if they are external URLs.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
